# Generated by Django 6.0.6 on 2026-06-17 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('pengarang', models.CharField(max_length=100)),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('penerbit', models.CharField(blank=True, max_length=100, null=True)),
                ('tahun_terbit', models.DateField(blank=True, null=True)),
                ('rak', models.CharField(blank=True, max_length=50, null=True)),
                ('stok', models.IntegerField(default=0)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buku_siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=20)),
                ('nis', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('jatuh_tempo', models.DateField()),
                ('keperluan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('dipinjam', 'Dipinjam'), ('dikembalikan', 'Dikembalikan'), ('terlambat', 'Terlambat')], default='dipinjam', max_length=20)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.buku')),
                ('buku_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.buku_siswa')),
            ],
        ),
    ]
